# Generated by Django 5.1.7 on 2025-03-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TAUser',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('tc_no', models.CharField(max_length=11, unique=True)),
                ('iban', models.CharField(blank=True, max_length=34, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('advisor', models.CharField(blank=True, max_length=255, null=True)),
                ('program', models.CharField(choices=[('MS', 'MS'), ('PhD', 'PhD')], max_length=3)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('isTA', models.BooleanField(default=True)),
                ('workload', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'ta_users',
            },
        ),
    ]
