# Generated by Django 5.1.7 on 2025-03-21 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffUser',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('isTA', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'staff_users',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('must_have_tas', models.ManyToManyField(blank=True, related_name='must_have_for_courses', to='myapp.tauser')),
                ('preferred_tas', models.ManyToManyField(blank=True, related_name='preferred_for_courses', to='myapp.tauser')),
                ('instructors', models.ManyToManyField(blank=True, related_name='courses_taught', to='myapp.staffuser')),
            ],
        ),
        migrations.CreateModel(
            name='TAWeeklySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('time_slot', models.CharField(max_length=20)),
                ('course', models.CharField(blank=True, max_length=50, null=True)),
                ('ta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_slots', to='myapp.tauser')),
            ],
        ),
    ]
