# Generated by Django 5.1.7 on 2025-03-20 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_staffuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='TAWeeklySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('time_slot', models.CharField(max_length=20)),
                ('course', models.CharField(blank=True, max_length=50, null=True)),
                ('ta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_slots', to='myapp.tauser')),
            ],
        ),
    ]
