# Generated by Django 5.1.7 on 2025-03-29 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='TADuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_type', models.CharField(choices=[('lab', 'Lab'), ('grading', 'Grading'), ('recitation', 'Recitation'), ('office_hours', 'Office Hours'), ('exam_proctoring', 'Proctoring'), ('other', 'Other')], default='other', help_text='Type of duty performed.', max_length=20)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('description', models.TextField(blank=True, help_text='Additional details or comments about the duty.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Current status (pending, approved, or rejected).', max_length=20)),
                ('course', models.ForeignKey(blank=True, help_text='Course related to the duty (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.course')),
                ('ta_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='myapp.tauser')),
            ],
            options={
                'db_table': 'ta_duties',
            },
        ),
    ]
