# Generated by Django 5.1.7 on 2025-04-01 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_taduty'),
    ]

    operations = [
        migrations.CreateModel(
            name='TALeaveRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('medical', 'Medical'), ('conference', 'Conference'), ('vacation', 'Vacation'), ('other', 'Other')], default='other', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('description', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='ta_leaves/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ta_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='myapp.tauser')),
            ],
            options={
                'db_table': 'ta_leaves',
            },
        ),
    ]
