# Generated by Django 5.1.7 on 2025-04-02 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_taleaverequests'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctoringAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoringassignment', to='myapp.exam')),
                ('ta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctored_exams', to='myapp.tauser')),
            ],
            options={
                'db_table': 'proctoring',
            },
        ),
    ]
