# Generated by Django 5.1.7 on 2025-04-15 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='TAAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_load', models.PositiveIntegerField(default=0, help_text='Minimum workload required from a TA in this course.')),
                ('max_load', models.PositiveIntegerField(default=0, help_text='Maximum workload allowed for a TA in this course.')),
                ('num_graders', models.PositiveIntegerField(default=1, help_text='Number of graders needed for this course.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avoided_tas', models.ManyToManyField(blank=True, help_text='TAs that should be avoided for this course.', related_name='avoided_assignments', to='myapp.tauser')),
                ('course', models.ForeignKey(help_text='Course for which TAs are being assigned.', on_delete=django.db.models.deletion.CASCADE, related_name='assignment_configs', to='myapp.course')),
                ('must_have_ta', models.ManyToManyField(blank=True, help_text='TAs that must be assigned to this course.', related_name='must_have_assignments', to='myapp.tauser')),
                ('preferred_graders', models.ManyToManyField(blank=True, help_text='List of TAs that are preferred as graders for this course.', related_name='preferred_graders_assignments', to='myapp.tauser')),
                ('preferred_tas', models.ManyToManyField(blank=True, help_text='List of TAs that are preferred for this course.', related_name='preferred_assignment_configs', to='myapp.tauser')),
                ('staff', models.ForeignKey(help_text='Instructor who configures TA assignment for this course.', on_delete=django.db.models.deletion.CASCADE, related_name='ta_assignments', to='myapp.staffuser')),
            ],
            options={
                'verbose_name': 'TA Assignment Configuration',
                'verbose_name_plural': 'TA Assignment Configurations',
                'unique_together': {('staff', 'course')},
            },
        ),
    ]
