# Generated by Django 5.1.7 on 2025-04-15 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_taassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='must_have_tas',
        ),
        migrations.RemoveField(
            model_name='course',
            name='preferred_tas',
        ),
    ]
