# Generated by Django 5.1.7 on 2025-04-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_course_must_have_tas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tauser',
            name='load',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tauser',
            name='ta_type',
            field=models.CharField(blank=True, choices=[('FT', 'Full-time'), ('PT', 'Part-time')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='taassignment',
            name='num_graders',
            field=models.PositiveIntegerField(default=0, help_text='Number of graders needed for this course.'),
        ),
    ]
