# Generated by Django 5.1.7 on 2025-04-16 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_tauser_load_tauser_ta_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taassignment',
            name='max_load',
            field=models.IntegerField(default=0, help_text='Maximum load allowed for TA(s) in this course.'),
        ),
        migrations.AlterField(
            model_name='taassignment',
            name='min_load',
            field=models.IntegerField(default=0, help_text='Minimum load allowed for TA(s) in this course.'),
        ),
        migrations.AlterField(
            model_name='taassignment',
            name='num_graders',
            field=models.IntegerField(default=0, help_text='Number of graders needed for this course.'),
        ),
        migrations.CreateModel(
            name='TAAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_tas', models.ManyToManyField(related_name='allocations', to='myapp.tauser')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ta_allocations', to='myapp.course')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ta_allocations', to='myapp.staffuser')),
            ],
        ),
    ]
