# Generated by Django 5.1.7 on 2025-04-16 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_taassignment_max_load_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taallocation',
            name='assigned_graders',
            field=models.ManyToManyField(blank=True, related_name='grader_allocations', to='myapp.tauser'),
        ),
        migrations.AlterField(
            model_name='taallocation',
            name='assigned_tas',
            field=models.ManyToManyField(related_name='ta_allocations', to='myapp.tauser'),
        ),
        migrations.AlterField(
            model_name='taallocation',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ta_allocation_course', to='myapp.course'),
        ),
        migrations.AlterField(
            model_name='taallocation',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ta_allocation_staff', to='myapp.staffuser'),
        ),
    ]
