# Generated by Django 5.1.7 on 2025-04-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_taallocation_assigned_graders_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedUser',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('SECRETARY', 'Secretary'), ('DEAN', 'Dean'), ('ADMIN', 'Admin')], max_length=20)),
                ('isTA', models.BooleanField(default=False)),
                ('isAuth', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'authorized_users',
            },
        ),
        migrations.RemoveField(
            model_name='tauser',
            name='load',
        ),
    ]
