# Generated by Django 5.1.7 on 2025-04-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_exam_classroom_name_exam_classrooms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentList',
            fields=[
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('courses', models.ManyToManyField(blank=True, related_name='students', to='myapp.course')),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
