# Generated by Django 5.1.7 on 2025-04-19 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_studentlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeanExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_codes', models.JSONField(default=list, help_text='List of course codes from NonDeptCourseEnum')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('num_proctors', models.PositiveIntegerField(default=1)),
                ('student_count', models.PositiveIntegerField(default=0)),
                ('classrooms', models.JSONField(default=list, help_text='List of room codes from ClassroomEnum')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams_created', to='myapp.authorizeduser')),
            ],
        ),
    ]
