# Generated by Django 5.1.7 on 2025-04-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_deanexam'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlist',
            name='nondept_courses',
            field=models.JSONField(blank=True, default=list, help_text='List of non-departmental course codes from NonDeptCourseEnum'),
        ),
    ]
