# Generated by Django 5.1.7 on 2025-04-22 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_swaprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='swaprequest',
            name='requested_by_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_swaps_made', to='myapp.authorizeduser'),
        ),
    ]
