# Generated by Django 5.1.7 on 2025-04-22 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_swaprequest_requested_by_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swaprequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swap_requests_sent', to='myapp.tauser'),
        ),
    ]
