# Generated by Django 5.1.7 on 2025-04-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_swaprequest_requested_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='swaprequest',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='swaprequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('original_assignment',), name='only_one_pending_per_assignment'),
        ),
    ]
