# Generated by Django 5.1.7 on 2025-04-22 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_swaprequest_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='swaprequest',
            name='only_one_pending_per_assignment',
        ),
    ]
