# Generated by Django 5.1.7 on 2025-05-01 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_remove_swaprequest_only_one_pending_per_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='swaprequest',
            name='previous_ta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swap_as_previous_ta', to='myapp.tauser'),
        ),
    ]
