# Generated by Django 5.1.7 on 2025-05-04 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_swaprequest_previous_ta'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('current_semester', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('max_ta_workload', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'admin_settings',
            },
        ),
    ]
