# Generated by Django 5.1.7 on 2025-05-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_authlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='authlog',
            name='user',
        ),
        migrations.AddField(
            model_name='authlog',
            name='user_email',
            field=models.EmailField(default='', help_text='Email of the user who logged in/out', max_length=254),
        ),
        migrations.AddField(
            model_name='authlog',
            name='user_type',
            field=models.CharField(choices=[('TA', 'TA'), ('Staff', 'Staff'), ('Authorized', 'Authorized')], default='TA', help_text='Type of user (TA, Staff, Authorized)', max_length=20),
        ),
    ]
