# Generated by Django 5.1.7 on 2025-05-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_authlog_options_remove_authlog_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizeduser',
            name='role',
            field=models.CharField(choices=[('CS SECRETARY', 'CS Secretary'), ('IE SECRETARY', 'IE Secretary'), ('EEE SECRETARY', 'ME Secretary'), ('ME SECRETARY', 'EEE Secretary'), ('DEAN', 'Dean'), ('ADMIN', 'Admin')], max_length=20),
        ),
    ]
