# Generated by Django 5.1.7 on 2025-05-05 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_alter_authorizeduser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tauser',
            name='iban',
        ),
        migrations.RemoveField(
            model_name='tauser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='tauser',
            name='tc_no',
        ),
    ]
