# Generated by Django 5.1.7 on 2025-05-08 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_remove_tauser_iban_remove_tauser_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(help_text='Section number (e.g. 1, 2…)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='myapp.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='myapp.staffuser')),
            ],
            options={
                'ordering': ['course', 'number'],
                'unique_together': {('course', 'number')},
            },
        ),
    ]
