# Generated by Django 5.1.7 on 2025-05-08 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_section'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taallocation',
            unique_together={('staff', 'course')},
        ),
    ]
