# Generated by Django 5.1.7 on 2025-05-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_alter_taallocation_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='instructor',
        ),
        migrations.AddField(
            model_name='section',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='sections', to='myapp.staffuser'),
        ),
    ]
