# Generated by Django 5.1.7 on 2025-05-10 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_remove_section_instructor_section_instructors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='instructors',
        ),
        migrations.AddField(
            model_name='section',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='myapp.staffuser'),
        ),
    ]
