# Generated by Django 5.1.7 on 2025-04-15 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0007_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.PositiveIntegerField()),
                ('min_tas', models.PositiveIntegerField(default=1)),
                ('student_count', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.staffuser')),
            ],
            options={
                'unique_together': {('course', 'section')},
            },
        ),
        migrations.CreateModel(
            name='TASectionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(max_length=30)),
                ('load', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='taassignment.coursesection')),
                ('ta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tauser')),
            ],
            options={
                'unique_together': {('section', 'ta')},
            },
        ),
    ]
