# Generated by Django 5.1.7 on 2025-04-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taassignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesection',
            name='max_tas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
